version: '3.7'

# indent로 트리를 표시하므로 유의!

# 컴퓨터들
services:
  my-backend:
    build:
      context: .
      dockerfile: Dockerfile
    # volumes:
    #   - ./src:/myfolder/src
    ports:
      - 3000:3000
    env_file:
      - ./.env.prod

  # my-database:
  #   image: mysql:latest
  #   environment:
  #     MYSQL_DATABASE: 'mycloud'
  #     MYSQL_ROOT_PASSWORD: 'root'
  #   ports:
  #     - 3306:3306
